spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zfy0428/eureka.git
          search-paths:
          - configfiles
      label: dev
server:
  port: 8888
